<?php 
    $fields = [ 'firstname', 
        'lastname', 
        'email',
    ];
?>
<div class="row">
    <div class="col-xs-8">
        <table class="table table-condensed">
            <colgroup>
                <col class="col-xs-6">
                <col class="col-xs-6">
            </colgroup>
            <tbody>
            <?php foreach ($fields as $field): $element = $this->form->get($field); ?>
                <tr>
                	<th><?= $this->formLabel($element) ?></th>
                	<td><?= $this->formElement($element) ?></td>
                </tr>
        	<?php endforeach; ?>
        	</tbody>
        </table>
    </div>
</div>