<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bootstrap Modal &amp; Zend Form</h3>
            </div>
            <div class="panel-body">
            	<p>
            		How to use Bootstrap Modal with Zend Form.
            	</p>
                <p><a class="btn btn-success pull-right" href="<?= $this->url('application', ['action' => 'customer', 'id' => 1]) ?>">Demo &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
